Support/update README refactor in publish workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -35,7 +35,7 @@ jobs:
             printf '\n\n---\n' >> CHANGELOG.md
 
             printf "> Looking for changes of previous versions?  \n" >> CHANGELOG.md
-            printf "You can find them in the [changelog history](https://www.github.com/${GITHUB_REPOSITORY}#changelog-history).\n" >> CHANGELOG.md
+            printf "You can find them in the [changelog history](https://www.github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_REF_NAME}/CHANGELOG_history.md).\n" >> CHANGELOG.md
       
           elif echo "$first_line" | grep -qE '<!--\s*publish\s*=\s*false\s*-->' ; then
             echo "Publish flag read: false. Stopping publishing action."
@@ -76,7 +76,9 @@ jobs:
         run: |
           escaped_version_name=$(echo "${{ steps.properties.outputs.minecraft_version_name }}" | sed 's/(/\\(/g; s/)/\\)/g')
           echo "escaped_version_name=$escaped_version_name" >> "$GITHUB_OUTPUT"
-          mod_version_title="${{ steps.properties.outputs.mod_name_short }} ${{ steps.properties.outputs.mod_version }} + ${{ steps.properties.outputs.minecraft_version_name }}"
+          mod_version_number="${{ steps.properties.outputs.mod_version }} + ${{ steps.properties.outputs.minecraft_version_name }}"
+          mod_version_title="${{ steps.properties.outputs.mod_name_short }} $mod_version_number"
+          echo "mod_version_number=$mod_version_number" >> "$GITHUB_OUTPUT"
           echo "mod_version_title=$mod_version_title" >> "$GITHUB_OUTPUT"
 
       - uses: Kir-Antipov/mc-publish@v3.3
@@ -107,12 +109,15 @@ jobs:
           sed -i '$d' CHANGELOG.md
           sed -i '$d' CHANGELOG.md
           
+          known_changelog=false
+          
           if [[ -f CHANGELOG_history.md && -s CHANGELOG_history.md ]]; then
-            changelog_headline=$(sed -n '2p' CHANGELOG.md)
-            history_headline=$(head -n 1 CHANGELOG_history.md)
-            if [[ "$changelog_headline" == "$history_headline" ]]; then
-              echo "Changelog already in history. Skipping updates to CHANGELOG_history.md and README.md."
-              exit 0
+            changelog_headline=$(sed -n '1p' CHANGELOG.md)
+            history_headline_1=$(sed -n '1p' CHANGELOG_history.md)
+            history_headline_2=$(sed -n '2p' CHANGELOG_history.md)
+            if [[ "$changelog_headline" == "$history_headline_1" || "$changelog_headline" == "$history_headline_2" ]]; then
+              echo "Changelog already in history. Skipping updates to CHANGELOG_history.md."
+              known_changelog=true
             fi
           fi
       
@@ -130,23 +135,45 @@ jobs:
           cf_download_url="${{ steps.publish.outputs.curseforge-url }}"
           mr_anchor_title="Download (Modrinth):&#10;${{ steps.format_version_name.outputs.mod_version_title }}"
           cf_anchor_title="Download (Curseforge):&#10;${{ steps.format_version_name.outputs.mod_version_title }}"
-          mr_img_alt="Download on Modrinth: ${{ steps.format_version_name.outputs.mod_version_title }}"
-          cf_img_alt="Download on Curseforge: ${{ steps.format_version_name.outputs.mod_version_title }}"
-          formatted_download_line="<sub><p align=\"center\"><a title=\"$mr_anchor_title\" href=\"$mr_download_url\"><img alt=\"$mr_img_alt\" height=\"26\" width=\"26\" src=\"https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/cozy-minimal/available/modrinth_vector.svg\"></a><sup>&thinsp;&#x20;&#x8ce;&nbsp;&#x200a;&#x200a;&#x200a;&#x200a;</sup><a title=\"$cf_anchor_title\" href=\"$cf_download_url\"><img alt=\"$cf_img_alt\" height=\"26\" width=\"26\" src=\"https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/cozy-minimal/available/curseforge_vector.svg\"></a>&thinsp;&#x200a;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p></sub>"
+          formatted_download_line="  \n|<sub>[<img width=222 height=21 src='https://img.shields.io/badge/Download%20${{ steps.format_version_name.outputs.mod_version_number }}%20on%3A%20-%231e242a?style=flat'>](#most-recent-version)</sub>|<a title='Download (Modrinth):&#10;${{ steps.format_version_name.outputs.mod_version_title }}' href='$mr_download_url'><sub><img width=26 src='https://img.shields.io/badge/--%23032a?style=flat&logo=modrinth'></a></sub>|<a title='Download (Curseforge):&#10;${{ steps.format_version_name.outputs.mod_version_title }}' href='$cf_download_url'><sub><img width=26 src='https://img.shields.io/badge/--%23302a?style=flat&logo=curseforge'></sub></a>|\n|:---|---|---|\n"
           spacer_line_number=$(( $(wc -l < CHANGELOG.md) - 1 ))
           sed -i "${spacer_line_number}i\\
           $formatted_download_line" CHANGELOG.md
           
-          printf 'Writing changelog to CHANGELOG_history.md and README.md:'
+          printf 'Writing changelog to CHANGELOG_history.md:'
           printf '\n========================================\n'
           cat CHANGELOG.md
           printf '\n========================================\n'
           
-          cat CHANGELOG.md CHANGELOG_history.md > temp && mv temp CHANGELOG_history.md
-        
+          if [ "$known_changelog" = false ]; then
+            cat CHANGELOG.md CHANGELOG_history.md > temp && mv temp CHANGELOG_history.md
+          else
+            echo "Skipping writing to CHANGELOG_history.md as this version is already recorded."
+          fi
+          
+          second_line=$(sed -n '2p' CHANGELOG.md)
+          if [[ "$second_line" == \#* ]]; then
+              sed -i '2s/^#/##/' CHANGELOG.md
+          else
+              echo "Unexpected format in CHANGELOG.md: Line 2 does not start with #"
+          fi
+          if [[ "$second_line" == *: ]]; then
+              sed -i '2s/:/[*](#footnote-*):/' CHANGELOG.md
+          else
+              echo "Unexpected format in CHANGELOG.md: Line 2 does not end with :"
+          fi
+          
+          sed -i '$d' CHANGELOG.md
+          sed -i '$d' CHANGELOG.md
+          
+          printf 'Writing changelog to README.md:'
+          printf '\n========================================\n'
+          cat CHANGELOG.md
+          printf '\n========================================\n'
+          
           if [[ ! -f README.md || ! -s README.md ]]; then
             echo "$changelog_start_marker" > README.md
-            cat CHANGELOG_history.md >> README.md
+            cat CHANGELOG.md >> README.md
             echo "" >> README.md
             echo "$changelog_end_marker" >> README.md
           else
@@ -157,16 +184,19 @@ jobs:
                 echo "The CHANGELOG:START/END markers are in incorrect order and/or in the same line in README.md"
                 exit 1
               fi
-              sed -i "$((start_line+1)),$((end_line-1))d" README.md
-              sed -i "$((start_line))r CHANGELOG_history.md" README.md
+              if [[ $((end_line - start_line)) -le 1 ]]; then
+                  sed -i "$((start_line))r CHANGELOG.md" README.md
+              else
+                  sed -i "$((start_line+1)),$((end_line-1))d" README.md
+                  sed -i "$((start_line))r CHANGELOG.md" README.md
+              fi
+              sed -i "$((start_line + $(wc -l < CHANGELOG.md)))a\\" README.md README.md
+              echo "Successfully updated changelog section in README.md."
             elif [[ -z "$start_line" && -z "$end_line" ]]; then
-              echo "No CHANGELOG:START/END markers found in README.md. Appending changelog history with start and end markers at the bottom of the file."
-              echo "$changelog_start_marker" >> README.md
-              cat CHANGELOG_history.md >> README.md
-              echo "" >> README.md
-              echo "$changelog_end_marker" >> README.md
+              echo "No CHANGELOG:START/END markers found in README.md. Unable to update changelog section."
+              exit 1
             else
-              echo "Incomplete changelog history markers found in README.md"
+              echo "Incomplete changelog markers found in README.md. Both START and END markers are required."
               exit 1
             fi
           fi
