Update dependencies

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -15,7 +15,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v5
 
       - name: check for publish flag
         run: |
@@ -28,18 +28,17 @@ jobs:
               echo "Publish flag read: false. Stopping publishing action."
               exit 1
           else
-              echo "Missing publish flag in line 1. Skipping publishing action and exiting with error."
-              echo "Please add '<!--publish=true-->' or '<!--publish=false-->' to the first line of CHANGELOG.md."
-              exit 1
+            echo "Missing publish flag in line 1. Skipping publishing action and exiting with error."
+            echo "Please add \`<!--publish=true-->\` or \`<!--publish=false-->\` to the first line of CHANGELOG.md."
+            exit 1
           fi
         continue-on-error: false
 
       - name: set up JDK 21
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v5
         with:
-          distribution: 'adopt-hotspot'
+          distribution: 'microsoft'
           java-version: 21
-          # cache: 'gradle'
 
       - name: make gradle wrapper executable
         run: chmod +x ./gradlew
